#pragma once
#include <string>

const std::string splashScreenLogo =
"========================== A.N.D ==========================\n"
"\n"
"              __   __                          _ _ _             \n"
"       /`\\  .( o)-( o).  /`\\                  \/_/_/_/\\         \n"
"      / , \\(  _______  )/ , \\                \/_/_/_/\\/\\       \n"
"  ___/ /_\\ /`\"-------\"`\\ /_\\ \___            \/_/_/_/\\/\\/\\     \n"
"  `~//^\\~_`\\  <__ __>  /`_~/^\\\~`            \\_\\_\\_\\/\\/\\/   \n"
"         `~//^\\\\~`~//^\\\\~                    \\_\\_\\_\\/\\/    \n"
"                                              \\_\\_\\_\\/    \n"
"===========================================================\n\n"
"Loading Game ";

const std::string welcomeMessage =
"                     WELCOME TO A.N.D!\n"
"\n"
"    A.N.D is an open source Educational Math History and \n"
"    English word trivia game. Get ready to learn intere- \n"
"    sting facts about famous mathematicians, expand your \n"
"    vocobulary and get to the top of the leaderboard.\n"
"\n"
"    Good luck and have fun!\n";


const std::string mainMenuScreen =

"+=========================================================+\n"
"\|                       Main Menu                         \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |          [0] Login/Sign-Up                        |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |          [1] About A.N.D                          |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |          [2] About Devs                           |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |          [3] Toggle Music On\\Off                  |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |          [4] Exit Game                            |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";




const std::string aboutDevsScreen = 
"+=========================================================+\n"
"\|                   About Developers                      \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  |                                                   |  \|\n"
"\|  | [+]- Darshan Pillay                               |  \|\n"
"\|  |      \"Outside a dog a book is a mans              |  \|\n"
"\|  |       bestfriend. Inside a dog it\'s               |  \|\n"
"\|  |       too dark to read\"- Groucho Marx             |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  | [+]- Nevan Padayachee                             |  \|\n"
"\|  |      \"When something is important                 |  \|\n"
"\|  |       enough you do it even if the                |  \|\n"
"\|  |       odds aren\'t in your favour\"- Elon Musk      |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  |                                                   |  \|\n"
"\|  | [+]- Aqeel Madhi                                  |  \|\n"
"\|  |     \"Developing this game was a                   |  \|\n"
"\|  |      wonderful experience and I                   |  \|\n"
"\|  |      enjoyed working with my teammates\"           |  \|\n"
"\|  |                                                   |  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";


const std::string aboutANDScreen =
"+=========================================================+\n"
"\|                      About A.N.D                        \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|  A.N.D was developed as part of the major final   \|  \|\n"
"\|  \|  year project of the developers. The main aim     \|  \|\n"
"\|  \|  of A.N.D is to broaden the players English       \|  \|\n"
"\|  \|  vocabularly and expand their general knowle-     \|  \|\n"
"\|  \|  dge.                                             \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|  A.N.D consists of two game modes namely          \|  \|\n"
"\|  \|  Frogs and Flies and Math Trivia. Each            \|  \|\n"
"\|  \|  game mode has a leaderboard. Players can         \|  \|\n"
"\|  \|  attempt to best their friends and other          \|  \|\n"
"\|  \|  players by scoring the most points in a          \|  \|\n"
"\|  \|  game mode. Players are encouraged to             \|  \|\n"
"\|  \|  try the harder difficulty options as they        \|  \|\n"
"\|  \|  will be challenged more and earn points.         \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|  A.N.D is open-source and follows the GNU         \|  \|\n"
"\|  \|  public licence terms and conditions. You         \|  \|\n"
"\|  \|  are free to distribute and or change parts       \|  \|\n"
"\|  \|  of this program. The parts which are not cha-    \|  \|\n"
"\|  \|  nged must be attributed to the devs of A.N.D.    \|  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";



const std::string playerProfileScreen =
"+=========================================================+\n"
"\|                  Player Profile Menu                    \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [0] Login                                \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [1] Sign-Up                              \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [2] Play As Guest                        \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [3] Toggle Music On\\Off                  \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [4] Back To Main Menu                    \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";

const std::string gameSelectionScreen =
"+=========================================================+\n"
"\|                  Game Selection Menu                    \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [0] Frogs and Flies                      \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [1] Math Trivia                          \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [2] Leaderboards                         \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [3] Toggle Music On\\Off                  \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [4] Tutorial                             \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [5] Logout                               \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";

const std::string frogsAndFliesMenu = 
"+=========================================================+\n"
"\|                  Frogs And Flies Menu                   \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [0] Easy {60 seconds,1pt}                \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [1] Medium {35 seconds,3pts}             \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [2] Hard {15 seconds,7pts}               \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [3] Toggle Music On\\Off                  \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [4] Game Selection Menu                  \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";

const std::string mathTriviaMenu =
"+=========================================================+\n"
"\|                   Math Trivia Menu                      \|\n"
"\|=========================================================\|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"\|  +===================================================+  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [0] Easy {60 seconds,1pt}                \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [1] Medium {35 seconds,3pts}             \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [2] Hard {15 seconds,7pts}               \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [3] Toggle Music On\\Off                  \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|          [4] Game Selection Menu                  \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  \|                                                   \|  \|\n"
"\|  +===================================================+  \|\n"
"\|                                                         \|\n"
"\|                                                         \|\n"
"+=========================================================+\n";

const std::string frogsAndFliesLeaderboardBanner = 
	"+=========================================================+\n"
	"\|               Frogs and Flies Leaderboard               \|\n"
	"\|=========================================================\|\n";

const std::string mathTriviaLeaderboardBanner =
	"+=========================================================+\n"
	"\|                 Math Trivia Leaderboard                 \|\n"
	"\|=========================================================\|\n";

const std::string tutorialScreen =
"+============================================================+\n"
"\|                     A.N.D Tutorial                         \|\n"
"\|============================================================\|\n"
"\n"
"A.N.D has two game modes namely Math Trivia and Frogs and\n"
"Flies. In each mode you are given several True\\False ques-\n"
"tions several True or False and Multiple Choice questions\n"
"For each question you will have a fixed number of options \n"
"to pick from. Be careful with your input. Selecting an \n"
"option that does not exist will result in you losing many\n"
"points.\n\n"

"The questions in Math Trivia require no extra knowledge to\n"
"attempt. However Frogs And Flies uses the concepts of Ant-\n"
"nym, Synonym and Homonym in its questions. A synonym of a \n"
"word is another word which means exactly or nearly the same\n"
"thing as it. For example nice is a synonym of good. An anto-\n"
"nym of a word is another word which means the opposite of it.\n"
"For example good is an antonym of bad. A homonym of a word\n"
"is another word which has the same spelling or pronunciation\n"
"of it. For example Stalk in the sense of the part of a plant \n"
"is a homonym of Stalk in the sense of to harass someone.\n"
"For more information please select the tut video option.\n\n"

"[0] - Go to tutorial video \n"
"[1] - Cheat Codes \n"
"[2] - Back to Game Selection\n\n"

"Enter your choice...";